# Generated by Django 4.1.4 on 2024-02-03 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_site_device_video_device_is'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='user_is',
        ),
    ]
