# Generated by Django 4.1.4 on 2024-02-03 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_video_user_is'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
